[MAGIC_ENV]
Owner = Magic Software Enterprises Ltd
;User=WWBARIO
;User=MCARRASCO
User=RMARTINEZ
;User=JORDAZ
;User=ELUNA
;User=VRODRIGUEZ
;User=GMUNOZ
;User=JGARCIA
;User=egonzalez
;Password=
DateMode = E
;FIREFLYSECURITY = D:\security
InputPassword = N
InputDate = N
NumberOfRecentProjects = 20
DefaultProject =
StartApplication =
DeploymentMode = R
;terminal=8049
;terminal=8048
terminal=8097
;terminal=8046
;terminal=8032
;terminal=8109
;terminal=8071
;terminal=8031
;terminal=8076
;terminal=10908
DefaultDatabase = SQLite Database
TempDatabase = Memory
ISAMTransaction = N
DeadlockPrevent = N
ThousandSeparator = ,
DecimalSeparator = .
DateSeparator = /
TimeSeparator = :
ScreenModePrompt = :
Century = 1920
BatchPaintTime = 1000
RangePopTime = 10
TempPopTime = 10
IdleTime = 1
MenuCloseTimeout = 0
TaskCacheSize = 0
ConfirmAutoExit = N
AllowCreateInModify = Y
AllowUpdateInQuery = N
LocateModeQueryWarning = Y
CopyrightMessages = Y
RtUserCopyright =
ResidentINI = N
RtToolBarGUI = Y
LoadResidentFiles = N
DisplayFullMsgs = Y
CenterScreenInOnline = N
RepositionAfterModify = N
AccessEnvironment = Y
AccessColors = Y
AccessFonts = Y
AccessKeyboardMapping = Y
AccessServers = Y
AccessServices = Y
AccessVisualConnection = Y
AccessCommunications = Y
AccessDBMS = Y
AccessDatabases = Y
AccessLogging = Y
AccessLogicalNames = Y
AccessLanguages = Y
AccessPrinters = Y
AccessHTMLStyles = Y
AccessPrintAttributes = Y
AccessLogon = Y
SystemLogin = N
MDIClientEdge = Y
AllowTesting = N
;
LogoFile =
ConstFile = %SUPPORT%mgconstw.eng
HelpFile = %SUPPORT%mghelpw.chm
StudioColorDefinitionFile = %SUPPORT%clr_std.eng
RuntimeApplicationColorDefinitionFile = %SUPPORT%clr_rnt.eng
RuntimeInternalColorDefinitionFile = %SUPPORT%clr_int.eng
StudioFontDefinitionFile = %SUPPORT%fnt_std.eng
RuntimeApplicationFontDefinitionFile = %SUPPORT%fnt_rnt.eng
RuntimeInternalFontDefinitionFile = %SUPPORT%fnt_int.eng
StudioKeyboardMappingFile = %SUPPORT%act_std.eng
RuntimeKeyboardMappingFile = %SUPPORT%act_rnt.eng
HTMLStyle =
PrintAttr = %SUPPORT%prn_std.eng
UsersPath = %SUPPORT%usr_std_qa.eng
;OEM2AnsiFile = %SUPPORT%OEM2Ansi.eng
;CollatingFile = %SUPPORT%acs_pc.eng
StartingLanguage =
DifferencesToolCommandLine =
;

ActivateRequestsServer = N
;Filters = HTTP_endusers:10% | SOAP_primary:20% | SOAP_secondary:10% | +
RemoteCalls_external:20% | RemoteCalls_internal:10% | COM:10%
MessagingServer = Default Broker
RequesterTimeout = 0
WebDocumentPath =
InternetDispatcherPath =
WebDocumentAlias =

IndentCharacters = 3
FileHandles = 0
CommandProcessor = C:\WINDOWS\system32\cmd.exe
LockFile  = mglock.dat
ResourceLockFilePath = mgres.loc
LockWithinTran = Y
LicenseFile = D:\uniPaaS\Studio\license.dat
LicenseName = MGCSTK
TooltipTimeout = 5
AuthoringToolPath = Notepad.exe
MaxBookMarks = 10
MaxCrfResults = 22
MaxConcurrentRequests = 0
ContextInactivityTimeout = 864000
ContextUnloadTimeout = 1200
RetryOperationTime = 600
GeneralErrorLog = D:\Usuarios\c-hmartinez\SUCV80\Iamsa-postgress\mgerror.log
DBLOGFILE = D:\Usuarios\c-hmartinez\SUCV80\Iamsa-postgress\mglogdb1.log

IOTiming = I
HTTPTimeout = 0
PBImagesNumber = 4

PalettesAlwaysOnTop = Y
DockablePalettes = Y
SingleExpandPalettes = N
AutomaticPropertySheet = F
LoadBalancingPriority = 3
MailConnectionTimeout = 0
MailOperationTimeout = 0
ImageCacheSize = 256
ImageCacheCheckTime = N
CheckerLevel = R
CheckerGroups = O
CheckerMessageTable = %SUPPORT%chk_std.dat
CheckerJumpAuto = Y
CheckerUnusedExp = O
CheckerOutputFile =
DropUserFormats =
AccessCheckerMessages = Y
LdapAddress =
LdapConnectionString =
LdapDomainContext =
LdapTimeout = 0
CTLCacheFilesPath = D:\uniPaaS\Studio\Browser_Client_Cache
CTLCacheFilesAlias = /uniBCCache
UseWindowsXPThemes = Y
OpenComponentsUsing = C
StudioStartupMode = W
DefaultSourceDir = Source
DefaultExportsDir = Exports
ExternalCodePage = 1252
SoapClientModulesPath = SoapClientModules\
EmbedFonts = Y
CompressPDF = Y
RCCloseTaskOnParent = N
DBDEBUG = Y
DBNOPARAMS = Y

[MAGIC_SERVERS]
Default Broker = 0,,,SUCDES02//1-25-2011//14:11:57,10,,1
DEFAULT = 0,,,,10,,1

[MAGIC_COMMS]
NONE = 1, 0, NO Parameters needed
TCP/IP = 2, 30, 1500-2000

[MAGIC_DBMS]
Btrieve = 1, NotAllowNull, 10.3, Btrieve Parameters, N, , NotLogSync, 0, +
0, NotCheckExist,
Pervasive = 2, NotAllowNull, 10.3, Pervasive Parameters, N, , NotLogSync, +
0, 0, NotCheckExist,
MySQL   = 4, NotAllowNull, 10.3, MySQL Parameters,,,,0,0,,
DB2/400 = 7, NotAllowNull, 10.3, DB2/400 Parameters, N, , NotLogSync, 0, +
0, NotCheckExist,
Oracle = 14, NotAllowNull, 10.3, Oracle Parameters, N, , NotLogSync, 0, +
0, NotCheckExist,
AS400 = 17, NotAllowNull, 10.3, LANGUAGE=%SUPPORT%AS2EB.eng, N, , +
NotLogSync, 1, 0, NotCheckExist, %SUPPORT%ACS400.eng
DB2 = 19, NotAllowNull, 10.3, DB2 Parameters, N, , NotLogSync, 999, 1, +
NotCheckExist,
ODBC = 20, NotAllowNull, 10.3, ODBC Parameters, N, , NotLogSync, 0, 0, +
NotCheckExist,
MicrosoftSQLServer = 21, NotAllowNull, 10.3, MicrosoftSQL Parameters, N, +
, NotLogSync, 0, 0, NotCheckExist,
Memory Tables = 22, NotAllowNull, 10.3, Memory Tables Parameters, N, , +
NotLogSync, 0, 0, NotCheckExist,
SQLite = 10, NotAllowNull, 10.3, SQLite Parameters, N, , NotLogSync, 0, +
1, CheckExist,

[MAGIC_DATABASES]
CITEC = DBMS, 22, PGAME, , 172.31.26.245, 5432, magicadm, PG-iam#dev01, CheckDefinition, NoCheckExist,
;CITEC = DBMS, 22, PGAME, , 172.31.26.3, 5432, magicadm, PG-iam#dev01, CheckDefinition, NoCheckExist,
;CITEC = DBMS, 22, postgres, , 172.31.24.35, 5432, postgres, BasePos01$, CheckDefinition, NoCheckExist,
;CITEC = DBMS, 22, postgres, , 172.31.24.35, 5432, PostgresVAB, BasePos01$, CheckDefinition, NoCheckExist,
;CITEC = DBMS, 19, DB2ETN, , , , magicadm, 4br1L.20003, CheckDefinition, NoCheckExist,
;CITEC = DBMS, 19, DB2VAB, , , , magicadm, 4br1L.20003, CheckDefinition, NoCheckExist,

[MAGIC_LOGICAL_NAMES]
Name1 = Translation1
Name2 = Translation2
LOGOS = D:\DIS\IMG\Imagenes\
BOT = D:\DIS\IMG\BOT\
IMG = D:\DIS\IMG\ETC\
MEN = D:\DIS\IMG\MEN\
INTERNET = D:\DIS\IMG\Imagenes\
path contable = Q:\DIS\confis\cont2000\
path servicios = Q:\DIS\confis\servicio\
path aplicación = Q:\DIS\confis\servicio\
blob = D:\ETN\blob\
RUTBIO = L:\mouse\
SWITCH = P:\ya
SWITCHRESP = P:\RESPALDOS\
SWITCHPEND = P:\PENDIENTES\
RUTPIN = L:\Lector\
Esquema = plugins
Esquema1 = plugins
EsquemaDAL = magicadm
Empresa = ETN
SUPPORT = Q:\DIS\Config_uniPaaS\
Version = Q:\IAMSA\
;Componente_MMTCC = %Version%01_MMTCC\
;Componente_MCG = %Version%02_MCG\
;Componente_MC = %Version%03_MC\
;Componente_MCT = %Version%04_MCT\
;Componente_MCI = %Version%05_MCI\
;Componente_MCWS = %Version%06_MCWS\
;Componente_MPS = %Version%07_MPS\
;Componente_MLC = %Version%08_MLC\
;Componente_MPA = %Version%09_MPA\
;Componente_MCA = %Version%10_MCA\
;Componente_MAC = %Version%11_MAC\
;Componente_MUYH = %Version%12_MUYH\
;Componente_MSAP = %Version%13_MSAP\
;Seguridad = %Version%14_SEGURIDAD\ECF\
;pathk = %Version%14_Seguridad\
;sucbd = DB2CTR
;sucbd = DB2VAB
;sucbd = DB2ARS
;sucbd = DB2ERS
sucbd = DB2ETN
;sucdb = DB2ETNRM
;sucbd = DB2TAP
;sucbd = DB2AME
;sucbd = DB2HAME
;sucbd = DB2PAR
;sucbd = DB2HP
;sucbd = DB2SUC
sucbdpass = %PASSDB%
sucbduser = magicadm
passdbold = 4br1L.20003
;navegantews = Q:\DIS\
;navegantews = D:\ETN\
navegantews = D:\DIS\
wsdl = %navegantews%wsdl\
xsd = %navegantews%xsd\
ipboleteraArs = 10.4.12.50
usuarioboleteraARS = boleteras
passboleteraARS= boleSQL
CONCILIAOPENPAY=NO
OFICINASWEB=NO
cudi = D:\DIS\SUCV80\Iamsa
RutaOficinas =D:\DIS\SUCV80\Iamsa
EJECUTACUDIWS=NO
CUDIDEPOSITOSCAMINO=NO

[MAGIC_PRINTERS]
Printer1 = ,%SUPPORT%lj3.atr,,60
Printer2 = laser_printer,%SUPPORT%epson.atr,,40
Printer3 = (server),,,66
Printer4 = (server)printer2,,,60
USB = ETNBOLETOS/Tarantella/Sesión 13,,,0
OdeM = ,,,0
OMex = ,,,0
ETNBOLETOS = ETNBOLETOS/Tarantella/Sesión 34,,,60
impresora002 = impresora002/Tarantella/Sesión 34,,,60


[MAGIC_LANGUAGE]

[MAGIC_LANGUAGE]

[MAGIC_SERVICES]
Default Service = Default Broker,,,
Soap citec Service = SOAP LITE,http://201.116.173.74:30000/Magic94Scripts/mgrqispi94.dll,,
Soap RecargasServiceService Service = SOAP LITE,http://www.k-eex.com.mx:8080/PlataformaSPVDesarollo/RecargasServiceService,,
Soap Integracion Service = SOAP LITE,http://www.k-eex.com.mx:8080/pagoServicios/Integracion,,
AMEX Service = SOAP LITE,https://qwww318.americanexpress.com/IPPayments/inter/services/AuthorizationService,,,,,,0,M,
Soap EmisionExternalService Service = SOAP LITE,http://www.pegasotecnologiacfdi.net/IAMSAEmisionGatewayQA/ServiceGateway.svc/Soap11Text,,,,,,0,M,

Soap EmisionExternalService Service = SOAP LITE,http://www.pegasotecnologiacfdi.net/IAMSAEmisionGatewayQA/ServiceGateway.svc/Soap11Text,,,,,,0,M,
Soap OpenAPIService Service = SOAP LITE,http://178.197.10.214:7603/OPM/OpenAPI/services,,
SOAP SAP CRM 01 = SOAP,http://SAPCRMDEV.iamsa.com.mx:8800/sap/bc/srt/rfc/sap/zcrm_wsdl_consumo_saldo_conve/100/zcrm_wsdl_consumo_saldo_conve/bind_zcrm_wsdl_consumo_saldo_conve,,,,http://sapcrmdev.iamsa.com.mx:8800/sap/bc/srt/wsdl/srvc_51CD391B219B1280E10080000A02038C/wsdl11/allinone/standard/document?sap-client=100&sap-user=WS_USER&sap-password=WS_USER,SOAP SAP CRM 01.jar,0,M,
SOAP SAP CRM 02 = SOAP,http://SAPCRMDEV.iamsa.com.mx:8800/sap/bc/srt/rfc/sap/zcrm_wsdl_consul_saldos/100/zcrm_wsdl_consul_saldos/bind_zcrm_wsdl_consul_saldos,,,,http://sapcrmdev.iamsa.com.mx:8800/sap/bc/srt/wsdl/srvc_51C1423318EE07C0E10080000A02038C/wsdl11/allinone/standard/document?sap-client=100&sap-user=WS_USER&sap-password=WS_USER,SOAP SAP CRM 02.jar,0,M,
SOAP SAP CRM 03 = SOAP,http://SAPCRMDEV.iamsa.com.mx:8800/sap/bc/srt/rfc/sap/zcrm_wsdl_recarga_saldos_copaq/100/zcrm_wsdl_recarga_saldos_copaq/bind_zcrm_wsdl_recarga_saldos_copaq,,,,http://sapcrmdev.iamsa.com.mx:8800/sap/bc/srt/wsdl/srvc_51BFC99E28130960E10080000A02038C/wsdl11/allinone/standard/document?sap-client=100&sap-user=WS_USER&sap-password=WS_USER,SOAP SAP CRM 03.jar,0,M,
SOAP SAP CRM 04 = SOAP,http://SAPCRMDEV.iamsa.com.mx:8800/sap/bc/srt/rfc/sap/zcrm_wsdl_alta_cotizacion/100/zcrm_wsdl_alta_cotizacion/zcrm_wsdl_alta_cotizacion,,,,http://sapcrmdev.iamsa.com.mx:8800/sap/bc/srt/wsdl/srvc_5211595CBFEC0660E10080000A02038C/wsdl11/allinone/standard/document?sap-client=100&sap-user=WS_USER&sap-password=WS_USER,SOAP SAP CRM 04.jar,0,M,
SOAP SAP CRM 05 = SOAP,http://SAPCRMDEV.iamsa.com.mx:8800/sap/bc/srt/rfc/sap/zcrm_wsdl_crear_interloc_com/100/zcrm_wsdl_crear_interloc_com/zcrm_wsdl_crear_interloc_com,,,,http://sapcrmdev.iamsa.com.mx:8800/sap/bc/srt/wsdl/srvc_5215BD727BF30E90E10080000A02038C/wsdl11/allinone/standard/document?sap-client=100&sap-user=WS_USER&sap-password=WS_USER,SOAP SAP CRM 05.jar,0,M,
SOAP SAP CRM 06 = SOAP,http://SAPCRMDEV.iamsa.com.mx:8800/sap/bc/srt/rfc/sap/zcrm_wsdl_actualiz_int_lealtad/100/zcrm_wsdl_actualiz_int_lealtad/bind_zcrm_wsdl_actualiz_int_lealtad,,,,http://sapcrmdev.iamsa.com.mx:8800/sap/bc/srt/wsdl/srvc_51CD487B219D1530E10080000A02038C/wsdl11/allinone/standard/document?sap-client=100&sap-user=WS_USER&sap-password=WS_USER,SOAP SAP CRM 06.jar,0,M,
SOAP SAP CRM 07 = SOAP,http://SAPCRMDEV.iamsa.com.mx:8800/sap/bc/srt/rfc/sap/zcrm_wsdl_lectura_int_lealtad/100/zcrm_wsdl_lectura_int_lealtad/bind_zcrm_wsdl_lectura_int_lealtad,,,,http://sapcrmdev.iamsa.com.mx:8800/sap/bc/srt/wsdl/srvc_51BFC40C28130960E10080000A02038C/wsdl11/allinone/standard/document?sap-client=100&sap-user=WS_USER&sap-password=WS_USER,SOAP SAP CRM 07.jar,0,M,
SOAP SAP CRM 08 = SOAP,http://SAPCRMDEV.iamsa.com.mx:8800/sap/bc/srt/rfc/sap/zcrm_wsdl_consul_sald_prglealt/100/zcrm_wsdl_consul_sald_prglealt/zcrm_wsdl_consul_sald_prglealt,,,,http://sapcrmdev.iamsa.com.mx:8800/sap/bc/srt/wsdl/srvc_521A5C27709217F0E10080000A02038C/wsdl11/allinone/standard/document?sap-client=100&sap-user=WS_USER&sap-password=WS_USER,SOAP SAP CRM 08.jar,0,M,
SOAP SAP CRM 09 = SOAP,http://SAPCRMDEV.iamsa.com.mx:8800/sap/bc/srt/rfc/sap/zcrm_wsdl_consul_detal_mvmt_pl/100/zcrm_wsdl_consul_detal_mvmt_pl/zcrm_wsdl_consul_detal_mvmt_pl,,,,http://sapcrmdev.iamsa.com.mx:8800/sap/bc/srt/wsdl/srvc_521A5C6F709217F0E10080000A02038C/wsdl11/allinone/standard/document?sap-client=100&sap-user=WS_USER&sap-password=WS_USER,SOAP SAP CRM 09.jar,0,M,
SOAP SAP CRM 10 = SOAP,http://SAPCRMDEV.iamsa.com.mx:8800/sap/bc/srt/rfc/sap/zcrm_wsdl_acum_ptos_prgm_lealt/100/zcrm_wsdl_acum_ptos_prgm_lealt/zcrm_wsdl_acum_ptos_prgm_lealt,,,,http://sapcrmdev.iamsa.com.mx:8800/sap/bc/srt/wsdl/srvc_5219A50CEA191DE0E10080000A02038C/wsdl11/allinone/standard/document?sap-client=100&sap-user=WS_USER&sap-password=WS_USER,SOAP SAP CRM 10.jar,0,M,
SOAP SAP CRM 11 = SOAP,http://SAPCRMDEV.iamsa.com.mx:8800/sap/bc/srt/rfc/sap/zcrm_wsdl_validar_promociones/100/zcrm_wsdl_validar_promociones/zcrm_wsdl_validar_promociones,,,,http://sapcrmdev.iamsa.com.mx:8800/sap/bc/srt/wsdl/srvc_5219A345EA191DE0E10080000A02038C/wsdl11/allinone/standard/document?sap-client=100&sap-user=WS_USER&sap-password=WS_USER,SOAP SAP CRM 11.jar,0,M,
Soap ITrpServerservice Service = SOAP LITE,https://sociosnegociodev.servicioscoordinados.com.mx/ISAPI/TrpServerV2014.dll/soap/ITrpServer,,
;Soap ITrpServerservice Service = SOAP LITE,http://200.34.32.31/scripts/TrpS+
;erverV2_01002002.dll/soap/ITrpServer,,

[MAGIC_GATEWAYS]
;MGDB00=D:\uniPaaS\Studio\Gateways\MGBtrieve.dll
;MGDB01=D:\uniPaaS\Studio\Gateways\MGPervasiveSQL.dll
;MGDB03=D:\uniPaaS\Studio\Gateways\MGMySQL.dll
;MGDB06=mgdb2400.DLL
MGDB09=D:\uniPaaS\Studio\Gateways\mgSQLite.dll
MGDB13=D:\uniPaaS\Studio\Gateways\mgOracle.dll
;MGDB16=mgeac32.dll
MGDB18=D:\uniPaaS\Studio\Gateways\mgdb2.DLL
MGDB19=D:\uniPaaS\Studio\Gateways\mgodbc.dll
MGDB20=D:\uniPaaS\Studio\Gateways\mgmssql.dll
MGDB21=D:\uniPaaS\Studio\Gateways\mgmemory.dll

[MAGIC_JAVA]
;JAVA_HOME=C:\Archivos de programa\Java\jre1.6.0_03\bin\
;JVM_PATH=
;CLASSPATH=%SUPPORT%uniUtils.jar;.;D:\ETN\XSD\gpayAPI.jar;D:\ETN\XSD\pasogpay.jar;.;D:\ETN\XSD\jar\ECorreo.jar;
;D:\ETN\XSD\jar\lib\mail.jarD:\ETN\XSD\jar\ECorreo.jar;D:\ETN\XSD\jar\lib\mail.jar;D:\ETN\XSD\WSAmex.jar;D:\ETN\xsd\jar\ECorreoN.jar;%SUPPORT%QRCode.jar;%SUPPORT%core.jar;
;JVM_ARGS=-Djava.compiler=NONE -Xms16m -Xmx256m -Dorg.xml.sax.driver=org.apa+
;che.xerces.parsers.SAXParser
;JAVA_HOME=C:\Archivos de programa\Java\jre1.6.0_03\bin\
;JAVA_HOME=C:\Program Files (x86)\Java\jre1.8.0_40\bin\
JVM_PATH=
CLASSPATH=%SUPPORT%uniUtils.jar;.;D:\ETN\xsd\gpayAPI.jar;D:\ETN\xsd\pasogpay.jar;D:\ETN\xsd\jar2\ECorreo.jar; +
D:\ETN\xsd\jar2\lib\mail.jar;D:\ETN\xsd\jar2\ECorreo.jar;D:\ETN\xsd\jar2\lib\mail.jar;D:\ETN\xsd\WSAmex.jar;D:\ETN\xsd\jar2\ECorreoN.jar;+
D:\ETN\xsd\SocketARS-Miller.jar;%SUPPORT%QRCode.jar;%SUPPORT%core.jar;
JVM_ARGS=-Djava.compiler=NONE -Xms16m -Xmx256m -Dorg.xml.sax.driver=org.apa+
che.xerces.parsers.SAXParser


[MAGIC_LOGGING]
Task = N
Levels = N
DataView = N
Recompute = N
Flow = N
Events = N
LogClient = N
TransCache = N
LogSynch = N
BeginEndMsg = N
Gateway = N
BackgroundMsg = N

[CRR_INTERFACES]
Web Service = Add_On\CRR\Wizards\CRRws.ecf, InvokeWizard, WS
Stored Procedure = Add_On\CRR\Wizards\CRRSp.ecf, InvokeWizard, StoredProc
Java Components = Add_On\CRR\Wizards\CRRjcg.ecf, InvokeWizard, JAVA
MSMQ Support = Add_On\CRR\Wizards\CRRMessaging.ecf,InvokeWizard, MSMQ


[TOOLS_MENU]
DDFMaker = A,&DDF Maker,,Add_On\DDFMaker\DDFMaker.ecf,,,Add_On\DDFMaker\DDF+
Maker_suf.opr,ImageFor = B ToolNumber = 60 ToolGroup = 1	ToolTip = +
"Create data dictionary file"
String Extractor = A,S&tring Extractor,,Add_On\StringExtractor\StringExtrac+
tor.ECF,,,,Ima+ geFor = B ToolNumber = 283 ToolGroup = 1	ToolTip = +
"Extract phrases for multi lingual dictionary"



[MAGIC_BUILDERS]
ECI=Builders\ECI\
EJB=Builders\EJB\
COM=Builders\COM\
WS=Builders\WS\
Soap Server Address = http://localhost:6060
SoapUser = admin

[DB2_SUC_CONNECTION]
;ETN DESA
Db2Connection = Bz1Z13nyb/pHCeu38+jMWwIXbTm4RusV1VHgpUnn8oRfgfP5RsIEqkpgAwB9Nh9KMBSM6BdJcAh0Q1kNxWAT6uwYwBTSsyn1nZcVFO2h5F4QeuYSWWtEZvWunzhRyCLWlbH7gwjNQU4V0XohRp7UQA==
ConnectionKey = U04WK28AIzLXP+oHlPuNHQ==


[POST_SUC_CONNECTION]
;PGAME
;PostConnection = 4SlHATMwoWVuJThQMBsiTQZQfbVseNmtYSukGn6icFPa/Zr+YlcXkGGIXiQVDwLH1Iaws3NEBMBIMpvHOrKAF5tu2SgZ/Y0ovDws9h2iadlx3wTE/KBUYeEu0SfoRIjg
;ConnectionKey = 1lEZ8zphZ5qxU5Q6IaJzKw==
;postgres
PostConnection = XYSxJWEokXLRSCXJ2JYLf6ikjHwhNk/5b+S1XSt+SfpSGJPphybSPezcxBlbyayUzi3itRDwg0puuHMUpjjMLcui5h8mBPPhcqSh3H255rZm4d4sBjg/Oom1YpppchN0
ConnectionKey = 0X4wbzPQ/8ieh6qdZ7zHUQ==
