
SELECT SUBSTR(TO_CHAR(CURRENT_DATE,'YYYY-MM-DD'),9,2) || '/' || SUBSTR(TO_CHAR(CURRENT_DATE,'YYYY-MM-DD'),6,2) || '/' || SUBSTR(TO_CHAR(CURRENT_DATE,'YYYY-MM-DD'),1,4);

SELECT TRIM(SUBSTR(CAST(statement_timestamp()::TIMESTAMP AS TEXT),12,2)) || ':' || TRIM(SUBSTR(CAST(statement_timestamp()::TIMESTAMP AS TEXT),15,2));

SELECT SUBSTR(TO_CHAR(CURRENT_DATE,'YYYY-MM-DD'),9,2) || '/' || SUBSTR(TO_CHAR(CURRENT_DATE,'YYYY-MM-DD'),6,2) || '/' || SUBSTR(TO_CHAR(CURRENT_DATE,'YYYY-MM-DD'),1,4);

SELECT TRIM(SUBSTR(CAST(statement_timestamp()::TIMESTAMP AS TEXT),12,2)) || ':' || TRIM(SUBSTR(CAST(statement_timestamp()::TIMESTAMP AS TEXT),15,2));

SELECT NNUMEROECONOMICO
FROM GCAUTOBUSES
WHERE NCLAVEEMPRESA =:1 AND NNUMEROECONOMICO =:2;

SELECT 
CASE AUT.NEMPRESAALTERNA
WHEN '2' THEN 'ETN'
WHEN '4' THEN 'AME'
WHEN '16' THEN 'TURISTAR'
WHEN '81' THEN 'DESARROLLO TERRESTRE MEXICANO'
WHEN '82' THEN 'DESARROLLO TERRESTRE MEXICANO'
WHEN '0' THEN 'NO_IDENTIFICADO'
END
FROM GCAUTOBUSES AUT
WHERE AUT.NCLAVEEMPRESA =:1 AND AUT.NNUMEROECONOMICO =:2;

SELECT SUBSTR(PSA.FCRFECHA,9,2) || '/' || SUBSTR(PSA.FCRFECHA,6,2) || '/' || SUBSTR(PSA.FCRFECHA,1,4)
FROM PSASIGNACIONVIAJE PSA
JOIN GCAUTOBUSES AUT ON(PSA.NCLAVEEMPRESA = AUT.NCLAVEEMPRESA AND PSA.NCLAVEAUTOBUS = AUT.NCLAVEAUTOBUS)
WHERE PSA.NCLAVEEMPRESA =:1 AND AUT.NNUMEROECONOMICO  =:2
ORDER BY PSA.FCRFECHA DESC
LIMIT 1;

SELECT SUBSTR(PSA.HCRHORA,1,2) || ':' || SUBSTR(PSA.HCRHORA,4,2) || ':' || SUBSTR(PSA.HCRHORA,7,2)
FROM PSASIGNACIONVIAJE PSA
JOIN GCAUTOBUSES AUT ON(PSA.NCLAVEEMPRESA = AUT.NCLAVEEMPRESA AND PSA.NCLAVEAUTOBUS = AUT.NCLAVEAUTOBUS)
WHERE PSA.NCLAVEEMPRESA =:1 AND AUT.NNUMEROECONOMICO  =:2
ORDER BY PSA.FCRFECHA DESC
LIMIT 1;

SELECT SUBSTR(CONCAT(', ',STRING_AGG(pun.ACLAVEOFICINA,', ')),3)
from PSCORRIDASACTIVAS act 
join PSPUNTOSTRAMOSCORR pun on (pun.NCLAVEEMPRESA = act.NCLAVEEMPESA and pun.NCLAVECORRIDA = act.NCLAVECORRIDA and pun.FFECHAINICIALAPLICACION = act.FFECHAINICIALAPLICACION)
LEFT JOIN GCAUTOBUSES AUT ON(AUT.NCLAVEEMPRESA = ACT.NCLAVEEMPESA AND AUT.NNUMEROECONOMICO =:2)
where act.NCLAVEEMPESA =:1 and ((act.NCLAVEAUTOBUSPLANEADO = AUT.NCLAVEAUTOBUS AND NCLAVEAUTOBUSSUSTITUTO = 0) OR NCLAVEAUTOBUSSUSTITUTO = AUT.NCLAVEAUTOBUS)
GROUP BY FFECHASALIDAINICIO,HHORASALIDAINICIO,ACT.NCLAVECORRIDA
order by FFECHASALIDAINICIO DESC,HHORASALIDAINICIO DESC
LIMIT 1;

SELECT PCR.ANOMBREROL 
FROM PSROLAUTOBUS PSR 
INNER JOIN PCROLES PCR ON (PCR.NCLAVEEMPRESA = PSR.NCLAVEEMPRESA AND PCR.NCLAVEROLINTERNA = PSR.NCLAVEROLINTERNA) 
INNER JOIN GCAUTOBUSES GCA ON (GCA.NNUMEROECONOMICO =:2 AND GCA.NCLAVEEMPRESA = PSR.NCLAVEEMPRESA) 
WHERE PSR.NCLAVEEMPRESA =:1 
AND PSR.NCLAVEAUTOBUS = GCA.NCLAVEAUTOBUS 
ORDER BY PSR.FAUFECHA DESC 
LIMIT 1;

SELECT trim(per.ANOMBRES) || ' ' || trim(per.AAPELLIDOS)
from ETTRIPULACION trip 
join GCPERSONAS per on (per.NCLAVEEMPRESA = trip.NCLAVEEMPRESA and per.NCLAVEPERSONA = trip.NCLAVEPERSONAASIGANDA)
join GCAUTOBUSES aut on (aut.NCLAVEEMPRESA = trip.NCLAVEEMPRESA and aut.NCLAVEAUTOBUS = trip.NCLAVEAUTOBUS)
where trip.NCLAVEEMPRESA =:1 and trip.NNUMEROCONDUCTOR = 1 and aut.NNUMEROECONOMICO =:2;

SELECT per.ACLAVEEMPLEADO
from ETTRIPULACION trip 
join GCPERSONAS per on (per.NCLAVEEMPRESA = trip.NCLAVEEMPRESA and per.NCLAVEPERSONA = trip.NCLAVEPERSONAASIGANDA)
join GCAUTOBUSES aut on (aut.NCLAVEEMPRESA = trip.NCLAVEEMPRESA and aut.NCLAVEAUTOBUS = trip.NCLAVEAUTOBUS)
where trip.NCLAVEEMPRESA =:1 and trip.NNUMEROCONDUCTOR = 1 and aut.NNUMEROECONOMICO =:2;

SELECT PTO.ATIPO
FROM ETTRIPULACION ETT
LEFT JOIN GCPERSONAS PER ON(ETT.NCLAVEEMPRESA = PER.NCLAVEEMPRESA AND ETT.NCLAVEPERSONAASIGANDA = PER.NCLAVEPERSONA)
LEFT JOIN GCAUTOBUSES AUT ON(ETT.NCLAVEEMPRESA = AUT.NCLAVEEMPRESA AND ETT.NCLAVEAUTOBUS = AUT.NCLAVEAUTOBUS)
LEFT JOIN PSTIPOSOPERADOR PTO ON(PER.NCLAVEEMPRESA = PTO.NCLAVEEMPRESA AND PER.TIPOOPERADOR = PTO.NCLAVETIPO)
WHERE ETT.NCLAVEEMPRESA =:1 AND AUT.NNUMEROECONOMICO =:2 AND ETT.NNUMEROCONDUCTOR = 1;

SELECT trim(PER.ATELEFONO1)
from ETTRIPULACION trip 
join GCPERSONAS per on (per.NCLAVEEMPRESA = trip.NCLAVEEMPRESA and per.NCLAVEPERSONA = trip.NCLAVEPERSONAASIGANDA)
join GCAUTOBUSES aut on (aut.NCLAVEEMPRESA = trip.NCLAVEEMPRESA and aut.NCLAVEAUTOBUS = trip.NCLAVEAUTOBUS)
where trip.NCLAVEEMPRESA =:1 and trip.NNUMEROCONDUCTOR = 1 and aut.NNUMEROECONOMICO =:2;

SELECT
bas.ANOMBREBASE
FROM GCPERSONAS PER
JOIN ETTRIPULACION TRI ON TRI.NCLAVEPERSONAASIGANDA = PER.NCLAVEPERSONA
JOIN GCAUTOBUSES AUT ON AUT.NCLAVEAUTOBUS = TRI.NCLAVEAUTOBUS
JOIN GCOFICINAS OFI ON OFI.ACLAVEOFICINA = PER.ACLAVEOFICINA and ofi.NCLAVEEMPRESA = per.NCLAVEEMPRESA
join GCBASES bas on bas.NCLAVEBASE = OFI.NCLAVEBASE
WHERE AUT.NNUMEROECONOMICO =:2 AND TRI.NNUMEROCONDUCTOR = 1;

SELECT
PER.FFECHAINGRESO
FROM GCPERSONAS PER
JOIN ETTRIPULACION TRI ON TRI.NCLAVEPERSONAASIGANDA = PER.NCLAVEPERSONA
JOIN GCAUTOBUSES AUT ON AUT.NCLAVEAUTOBUS = TRI.NCLAVEAUTOBUS
WHERE AUT.NNUMEROECONOMICO =:2 AND TRI.NNUMEROCONDUCTOR = 1;

SELECT 
CASE PER.NEMPRESAALTERNA
WHEN '2' THEN 'ETN'
WHEN '16' THEN 'TURISTAR'
WHEN '81' THEN 'DESARROLO TERRESTRE MEXICANO'
WHEN '82' THEN 'DESARROLO TERRESTRE MEXICANO'
WHEN '0' THEN 'NO_ESPECIFICADO'
END
FROM ETTRIPULACION ETT
LEFT JOIN GCPERSONAS PER ON(ETT.NCLAVEEMPRESA = PER.NCLAVEEMPRESA AND ETT.NCLAVEPERSONAASIGANDA = PER.NCLAVEPERSONA)
LEFT JOIN GCAUTOBUSES AUT ON(ETT.NCLAVEEMPRESA = AUT.NCLAVEEMPRESA AND ETT.NCLAVEAUTOBUS = AUT.NCLAVEAUTOBUS)
WHERE ETT.NCLAVEEMPRESA =:1 AND AUT.NNUMEROECONOMICO =:2 AND ETT.NNUMEROCONDUCTOR = 1;

SELECT et.ADESCRIPCION
FROM ETTRIPULACION ETT
LEFT JOIN GCPERSONAS PER ON(ETT.NCLAVEEMPRESA = PER.NCLAVEEMPRESA AND ETT.NCLAVEPERSONAASIGANDA = PER.NCLAVEPERSONA)
LEFT JOIN GCAUTOBUSES AUT ON(ETT.NCLAVEEMPRESA = AUT.NCLAVEEMPRESA AND ETT.NCLAVEAUTOBUS = AUT.NCLAVEAUTOBUS)
LEFT JOIN ETESTADOACTUALCOND eta ON(per.NCLAVEEMPRESA = eta.NCLAVEEMPRESA AND eta.NCLAVEPERSONA = per.NCLAVEPERSONA)
LEFT JOIN ETESTADOSCONDUCTOR et ON(eta.NCLAVEEMPRESA = et.NCLAVEEMPRESA AND eta.ACLAVEESTADOCONDUCTOR = et.ACLAVEESTADOCONDUCTOR)
WHERE ETT.NCLAVEEMPRESA =:1 AND AUT.NNUMEROECONOMICO =:2 AND ETT.NNUMEROCONDUCTOR = 1
ORDER BY eta.NCONSECUTIVO desc
LIMIT 1;

SELECT trim(per.ANOMBRES) || ' ' || trim(per.AAPELLIDOS)
from ETTRIPULACION trip 
join GCPERSONAS per on (per.NCLAVEEMPRESA = trip.NCLAVEEMPRESA and per.NCLAVEPERSONA = trip.NCLAVEPERSONAASIGANDA)
join GCAUTOBUSES aut on (aut.NCLAVEEMPRESA = trip.NCLAVEEMPRESA and aut.NCLAVEAUTOBUS = trip.NCLAVEAUTOBUS)
where trip.NCLAVEEMPRESA =:1 and trip.NNUMEROCONDUCTOR = 2 and aut.NNUMEROECONOMICO =:2;

SELECT per.ACLAVEEMPLEADO
from ETTRIPULACION trip 
join GCPERSONAS per on (per.NCLAVEEMPRESA = trip.NCLAVEEMPRESA and per.NCLAVEPERSONA = trip.NCLAVEPERSONAASIGANDA)
join GCAUTOBUSES aut on (aut.NCLAVEEMPRESA = trip.NCLAVEEMPRESA and aut.NCLAVEAUTOBUS = trip.NCLAVEAUTOBUS)
where trip.NCLAVEEMPRESA =:1 and trip.NNUMEROCONDUCTOR = 2 and aut.NNUMEROECONOMICO =:2;

SELECT PSA.NCLAVEASIGNACIONVIAJE
FROM PSCONDUCTORESVIAJE PSV
JOIN PSASIGNACIONVIAJE PSA ON(PSA.NCLAVEEMPRESA = PSV.NCLAVEEMPRESA AND PSA.NCLAVEASIGNACIONVIAJE = PSV.NCLAVEASIGNACION AND PSV.NCLAVEAUTOBUS = PSA.NCLAVEAUTOBUS)
WHERE PSA.NCLAVEEMPRESA =:1 AND PSV.NCLAVEPERSONA =:2
ORDER BY PSA.NCLAVEASIGNACIONVIAJE DESC,PSA.FCRFECHA DESC
LIMIT 1;

SELECT PTO.ATIPO
FROM ETTRIPULACION ETT
LEFT JOIN GCPERSONAS PER ON(ETT.NCLAVEEMPRESA = PER.NCLAVEEMPRESA AND ETT.NCLAVEPERSONAASIGANDA = PER.NCLAVEPERSONA)
LEFT JOIN GCAUTOBUSES AUT ON(ETT.NCLAVEEMPRESA = AUT.NCLAVEEMPRESA AND ETT.NCLAVEAUTOBUS = AUT.NCLAVEAUTOBUS)
LEFT JOIN PSTIPOSOPERADOR PTO ON(PER.NCLAVEEMPRESA = PTO.NCLAVEEMPRESA AND PER.TIPOOPERADOR = PTO.NCLAVETIPO)
WHERE ETT.NCLAVEEMPRESA =:1 AND AUT.NNUMEROECONOMICO =:2 AND ETT.NNUMEROCONDUCTOR = 2;

SELECT
bas.ANOMBREBASE
FROM GCPERSONAS PER
JOIN ETTRIPULACION TRI ON TRI.NCLAVEPERSONAASIGANDA = PER.NCLAVEPERSONA
JOIN GCAUTOBUSES AUT ON AUT.NCLAVEAUTOBUS = TRI.NCLAVEAUTOBUS
JOIN GCOFICINAS OFI ON OFI.ACLAVEOFICINA = PER.ACLAVEOFICINA and ofi.NCLAVEEMPRESA = per.NCLAVEEMPRESA
join GCBASES bas on bas.NCLAVEBASE = OFI.NCLAVEBASE
WHERE AUT.NNUMEROECONOMICO =:2 AND TRI.NNUMEROCONDUCTOR = 2;

SELECT
PER.FFECHAINGRESO
FROM GCPERSONAS PER
JOIN ETTRIPULACION TRI ON TRI.NCLAVEPERSONAASIGANDA = PER.NCLAVEPERSONA
JOIN GCAUTOBUSES AUT ON AUT.NCLAVEAUTOBUS = TRI.NCLAVEAUTOBUS
WHERE AUT.NNUMEROECONOMICO =:2 AND TRI.NNUMEROCONDUCTOR = 2;

SELECT 
CASE PER.NEMPRESAALTERNA
WHEN '2' THEN 'ETN'
WHEN '16' THEN 'TURISTAR'
WHEN '81' THEN 'DESARROLO TERRESTRE MEXICANO'
WHEN '82' THEN 'DESARROLO TERRESTRE MEXICANO'
WHEN '0' THEN 'NO_ESPECIFICADO'
END
FROM ETTRIPULACION ETT
LEFT JOIN GCPERSONAS PER ON(ETT.NCLAVEEMPRESA = PER.NCLAVEEMPRESA AND ETT.NCLAVEPERSONAASIGANDA = PER.NCLAVEPERSONA)
LEFT JOIN GCAUTOBUSES AUT ON(ETT.NCLAVEEMPRESA = AUT.NCLAVEEMPRESA AND ETT.NCLAVEAUTOBUS = AUT.NCLAVEAUTOBUS)
WHERE ETT.NCLAVEEMPRESA =:1 AND AUT.NNUMEROECONOMICO =:2 AND ETT.NNUMEROCONDUCTOR = 2;

SELECT et.ADESCRIPCION
FROM ETTRIPULACION ETT
LEFT JOIN GCPERSONAS PER ON(ETT.NCLAVEEMPRESA = PER.NCLAVEEMPRESA AND ETT.NCLAVEPERSONAASIGANDA = PER.NCLAVEPERSONA)
LEFT JOIN GCAUTOBUSES AUT ON(ETT.NCLAVEEMPRESA = AUT.NCLAVEEMPRESA AND ETT.NCLAVEAUTOBUS = AUT.NCLAVEAUTOBUS)
LEFT JOIN ETESTADOACTUALCOND eta ON(per.NCLAVEEMPRESA = eta.NCLAVEEMPRESA AND eta.NCLAVEPERSONA = per.NCLAVEPERSONA)
LEFT JOIN ETESTADOSCONDUCTOR et ON(eta.NCLAVEEMPRESA = et.NCLAVEEMPRESA AND eta.ACLAVEESTADOCONDUCTOR = et.ACLAVEESTADOCONDUCTOR)
WHERE ETT.NCLAVEEMPRESA =:1 AND AUT.NNUMEROECONOMICO =:2 AND ETT.NNUMEROCONDUCTOR = 2
ORDER BY eta.NCONSECUTIVO desc
LIMIT 1;

SELECT trim(PER.ATELEFONO1)
from ETTRIPULACION trip 
join GCPERSONAS per on (per.NCLAVEEMPRESA = trip.NCLAVEEMPRESA and per.NCLAVEPERSONA = trip.NCLAVEPERSONAASIGANDA)
join GCAUTOBUSES aut on (aut.NCLAVEEMPRESA = trip.NCLAVEEMPRESA and aut.NCLAVEAUTOBUS = trip.NCLAVEAUTOBUS)
where trip.NCLAVEEMPRESA =:1 and trip.NNUMEROCONDUCTOR = 2 and aut.NNUMEROECONOMICO =:2;

SELECT TRIM(trim(ofi.ACLAVEOFICINA) || '; ' || trim(ofi.ANOMBREOFICINA) || '; ' || trim(ofi.ACALLE) || '; ' || trim(ofi.ANUMERO) || '; ' || trim(ofi.ACOLONIA) || '; ' || trim(ofi.AMUNICIPIODELEG) || '; ' || trim(est.ADESCRIPCIONESTADO) || '; ' || ofi.NCODIGOPOSTAL)
from GCPERSONAS as per
join GCOFICINAS as ofi
on (per.NCLAVEEMPRESA = ofi.NCLAVEEMPRESA and per.ACLAVEOFICINA = ofi.ACLAVEOFICINA)
join GCESTADOS as est on (ofi.NCLAVEEMPRESA = est.NCLAVEEMPRESA and ofi.ACLAVEESTADO = est.ACLAVEESTADO)
where per.NCLAVEEMPRESA =:1 and per.NCLAVEPERSONA =:2;

SELECT TRIM(PER.ACLAVEEMPLEADO) || ' ' || TRIM(PER.ANOMBRES) || ' ' || TRIM(PER.AAPELLIDOS)  || ' ' || coalesce(per.ACLAVEOFICINA,' ')
FROM PAKARDEX KAR
JOIN PAADMONTAREAS TAR ON (TAR.NCLAVEEMPRESA = KAR.NCLAVEEMPRESA AND TAR.NIDFLUJO = KAR.NIDGENERALFLUJO)
JOIN GCPERSONAS PER ON (PER.NCLAVEEMPRESA = KAR.NCLAVEEMPRESA AND PER.ACLAVEUSUARIO = KAR.AAUCLAVEUSUARIO)
WHERE KAR.NCLAVEEMPRESA =:1 AND KAR.NIDGENERALFLUJO =:3 AND TAR.AESTATUS = 'T'
ORDER BY KAR.FAUFECHA DESC,KAR.HAUHORA DESC LIMIT 1;

SELECT PUE.ADENOMINACIONAREAPER
FROM MAGICADM.GCPERSONAS PER
LEFT JOIN MAGICADM.PAPUESTOS PUE ON (PUE.NEMPRESA = PER.NCLAVEEMPRESA AND PUE.NIDPUESTO = PER.NIDPUESTOSAP)
WHERE PER.NCLAVEEMPRESA =:1 AND PER.NCLAVEPERSONA =:2
LIMIT 1;

SELECT PUE.ATEXTODIVISIONPER
FROM MAGICADM.GCPERSONAS PER
LEFT JOIN MAGICADM.PAPUESTOS PUE ON (PUE.NEMPRESA = PER.NCLAVEEMPRESA AND PUE.NIDPUESTO = PER.NIDPUESTOSAP)
WHERE PER.NCLAVEEMPRESA =:1 AND PER.NCLAVEPERSONA =:2
LIMIT 1;

SELECT PUE.ADENOMINACIONGRUPOPER
FROM MAGICADM.GCPERSONAS PER
LEFT JOIN MAGICADM.PAPUESTOS PUE ON (PUE.NEMPRESA = PER.NCLAVEEMPRESA AND PUE.NIDPUESTO = PER.NIDPUESTOSAP)
WHERE PER.NCLAVEEMPRESA =:1 AND PER.NCLAVEPERSONA =:2
LIMIT 1;

SELECT PUE.ADENOMINACIONPUESTO
FROM MAGICADM.GCPERSONAS PER
LEFT JOIN MAGICADM.PAPUESTOS PUE ON (PUE.NEMPRESA = PER.NCLAVEEMPRESA AND PUE.NIDPUESTO = PER.NIDPUESTOSAP)
WHERE PER.NCLAVEEMPRESA =:1 AND PER.NCLAVEPERSONA =:2
LIMIT 1;

SELECT PUE.ASOCIEDAD
FROM MAGICADM.GCPERSONAS PER
LEFT JOIN MAGICADM.PAPUESTOS PUE ON (PUE.NEMPRESA = PER.NCLAVEEMPRESA AND PUE.NIDPUESTO = PER.NIDPUESTOSAP)
WHERE PER.NCLAVEEMPRESA =:1 AND PER.NCLAVEPERSONA =:2
LIMIT 1;

SELECT PUE.ATEXTOSUBDIVISIONPER
FROM MAGICADM.GCPERSONAS PER
LEFT JOIN MAGICADM.PAPUESTOS PUE ON (PUE.NEMPRESA = PER.NCLAVEEMPRESA AND PUE.NIDPUESTO = PER.NIDPUESTOSAP)
WHERE PER.NCLAVEEMPRESA =:1 AND PER.NCLAVEPERSONA =:2
LIMIT 1;

SELECT PUE.ADENOMINACIONUNIORG
FROM MAGICADM.GCPERSONAS PER
LEFT JOIN MAGICADM.PAPUESTOS PUE ON (PUE.NEMPRESA = PER.NCLAVEEMPRESA AND PUE.NIDPUESTO = PER.NIDPUESTOSAP)
WHERE PER.NCLAVEEMPRESA =:1 AND PER.NCLAVEPERSONA =:2
LIMIT 1;

SELECT trim(PER.ATELEFONO1)
from GCPERSONAS per
where per.NCLAVEEMPRESA =:1 and per.NCLAVEPERSONA =:2;

SELECT PER.NIMSS
from GCPERSONAS per
where per.NCLAVEEMPRESA =:1 and per.NCLAVEPERSONA =:2;

SELECT PST.ATIPO 
FROM GCPERSONAS  GCP 
INNER JOIN PSTIPOSOPERADOR PST ON (PST.NCLAVEEMPRESA = GCP.NCLAVEEMPRESA AND PST.NCLAVETIPO = GCP.TIPOOPERADOR) 
WHERE GCP.NCLAVEEMPRESA =:1 
AND GCP.NCLAVEPERSONA =:2;

SELECT trim(est.ADESCRIPCION)
from ETESTADOACTUALCOND ult
join ETESTADOSCONDUCTOR est on (est.NCLAVEEMPRESA = ult.NCLAVEEMPRESA and est.ACLAVEESTADOCONDUCTOR = ult.ACLAVEESTADOCONDUCTOR)
where ult.HFECHASERVIDOR <= CURRENT_DATE and  ult.NCLAVEEMPRESA =:1 and ult.NCLAVEPERSONA =:2 
order by ult.NCONSECUTIVO desc LIMIT 1;

SELECT GCE.NOMBRE FROM GCPERSONAS GCP INNER JOIN GCEMPRESAS GCE ON (GCE.CLAVEEMPRESA = GCP.NEMPRESAALTERNA) WHERE GCP.NCLAVEEMPRESA =:1 AND GCP.NCLAVEPERSONA =:2;

SELECT trim(bas.ANOMBREBASE)
from GCPERSONAS per
JOIN GCOFICINAS OFI ON (OFI.ACLAVEOFICINA = PER.ACLAVEOFICINA and ofi.NCLAVEEMPRESA = per.NCLAVEEMPRESA)
join GCBASES bas on (bas.NCLAVEBASE = OFI.NCLAVEBASE and bas.NCLAVEEMPRESA = per.NCLAVEEMPRESA)
where per.NCLAVEEMPRESA =:1 and per.NCLAVEPERSONA =:2;

SELECT per.ACLAVEEMPLEADO
from GCPERSONAS per
where per.NCLAVEEMPRESA =:1 and per.NCLAVEPERSONA =:2;

SELECT TRIM(PER.ANOMBRES) || ' ' || TRIM(PER.AAPELLIDOS)
FROM GCPERSONAS PER
WHERE PER.NCLAVEEMPRESA =:1 AND PER.NCLAVEPERSONA =:2;

SELECT PER.ACLAVEEMPLEADO
FROM GCPERSONAS PER
WHERE PER.NCLAVEEMPRESA =:1 AND PER.NCLAVEPERSONA =:2;

SELECT PCP.NVIAJE
FROM PSCONDUCTORESVIAJE PSV
JOIN PSASIGNACIONVIAJE PSA ON(PSA.NCLAVEEMPRESA = PSV.NCLAVEEMPRESA AND PSA.NCLAVEASIGNACIONVIAJE = PSV.NCLAVEASIGNACION AND PSV.NCLAVEAUTOBUS = PSA.NCLAVEAUTOBUS)
JOIN PSCORRIDASVIAJE PCV ON(PCV.NCLAVEENPRESA = PSA.NCLAVEEMPRESA AND PCV.NCLAVEASIGNACION = PSA.NCLAVEASIGNACIONVIAJE)
JOIN PSCORRIDASACTIVAS PCA ON(PCA.NCLAVEEMPESA = PCV.NCLAVEENPRESA AND PCA.NCLAVECORRIDA = PCV.NCLAVECORRIDA AND PCA.FFECHASALIDAINICIO = PCV.FFECHASALIDAINICIO AND PCA.NVERSION = PCV.NVERSION)
JOIN PSCORRIDASPERMANEN PCP ON(PCP.NCLAVEEMPRESA = PCA.NCLAVEEMPESA AND PCP.NCLAVECORRIDA = PCA.NCLAVECORRIDA AND PCP.NFFECHAINICIALAPLICACION = PCA.FFECHAINICIALAPLICACION)
WHERE PSV.NCLAVEEMPRESA =:1 AND PSV.NCLAVEPERSONA =:2 AND PCA.NREGENERACION = 0
ORDER BY PSA.NCLAVEASIGNACIONVIAJE DESC,PSA.FCRFECHA DESC
LIMIT 1;

SELECT ROL.ACLAVEROL
FROM PCROLES ROL
LEFT JOIN PSROLAUTOBUS RAUT ON(ROL.NCLAVEEMPRESA = RAUT.NCLAVEEMPRESA AND ROL.NCLAVEROLINTERNA = RAUT.NCLAVEROLINTERNA)
LEFT JOIN ETTRIPULACION ETT ON(RAUT.NCLAVEEMPRESA = ETT.NCLAVEEMPRESA AND ETT.NCLAVEAUTOBUS = RAUT.NCLAVEAUTOBUS)
WHERE ROL.NCLAVEEMPRESA =:1 AND ETT.NCLAVEPERSONAASIGANDA =:2;

SELECT count(ACT.NCLAVECORRIDA)
from PSCORRIDASACTIVAS act 
join PSPUNTOSTRAMOSCORR pun on (pun.NCLAVEEMPRESA = act.NCLAVEEMPESA and pun.NCLAVECORRIDA = act.NCLAVECORRIDA and pun.FFECHAINICIALAPLICACION = act.FFECHAINICIALAPLICACION)
LEFT JOIN ETTRIPULACION ETT ON(PUN.NCLAVEEMPRESA = ETT.NCLAVEEMPRESA AND ETT.NCLAVEPERSONAASIGANDA =:2)
where act.NCLAVEEMPESA =:1 and (NCLAVEPERSONAPOSTURERO1 = ETT.NCLAVEPERSONAASIGANDA OR NCLAVEPERSONAPOSTURERO2 = ETT.NCLAVEPERSONAASIGANDA OR 
(NCLAVEAUTOBUSPLANEADO = ETT.NCLAVEAUTOBUS AND NCLAVEAUTOBUSSUSTITUTO = 0)
OR NCLAVEAUTOBUSSUSTITUTO = ETT.NCLAVEAUTOBUS)
GROUP BY FFECHASALIDAINICIO,HHORASALIDAINICIO,ACT.NCLAVECORRIDA
order by FFECHASALIDAINICIO DESC,HHORASALIDAINICIO DESC
LIMIT 1;

SELECT SUBSTR(CONCAT(', ',STRING_AGG(pun.ACLAVEOFICINA,', ')),3)
from PSCORRIDASACTIVAS act 
join PSPUNTOSTRAMOSCORR pun on (pun.NCLAVEEMPRESA = act.NCLAVEEMPESA and pun.NCLAVECORRIDA = act.NCLAVECORRIDA and pun.FFECHAINICIALAPLICACION = act.FFECHAINICIALAPLICACION)
LEFT JOIN ETTRIPULACION ETT ON(PUN.NCLAVEEMPRESA = ETT.NCLAVEEMPRESA AND ETT.NCLAVEPERSONAASIGANDA =:2)
where act.NCLAVEEMPESA =:1 and (NCLAVEPERSONAPOSTURERO1 = ETT.NCLAVEPERSONAASIGANDA OR NCLAVEPERSONAPOSTURERO2 = ETT.NCLAVEPERSONAASIGANDA OR 
(NCLAVEAUTOBUSPLANEADO = ETT.NCLAVEAUTOBUS AND NCLAVEAUTOBUSSUSTITUTO = 0)
OR NCLAVEAUTOBUSSUSTITUTO = ETT.NCLAVEAUTOBUS)
GROUP BY FFECHASALIDAINICIO,HHORASALIDAINICIO,ACT.NCLAVECORRIDA
order by FFECHASALIDAINICIO DESC,HHORASALIDAINICIO DESC
LIMIT 1;

SELECT SUM(CCM.NMONTO)
FROM PSCONDUCTORESVIAJE PCV
JOIN PSASIGNACIONVIAJE PSA ON(PSA.NCLAVEEMPRESA = PCV.NCLAVEEMPRESA AND PSA.NCLAVEASIGNACIONVIAJE = PCV.NCLAVEASIGNACION)
JOIN CCMOVIMIENTOSNOMIN CCM ON(CCM.NCLAVEEMPRESA = PSA.NCLAVEEMPRESA AND PSA.NCLAVEASIGNACIONVIAJE = CCM.NCLAVEASIGNACION AND CCM.NCLAVEPERSONA = PCV.NCLAVEPERSONA)
WHERE PCV.NCLAVEEMPRESA =:1 AND PCV.NCLAVEPERSONA =:2
GROUP BY PSA.NCLAVEASIGNACIONVIAJE,PSA.FCRFECHA
ORDER BY PSA.NCLAVEASIGNACIONVIAJE DESC,PSA.FCRFECHA DESC
LIMIT 1;

SELECT SUBSTR(PCA.HHORASALIDAINICIO,1,2) || ':' || SUBSTR(PCA.HHORASALIDAINICIO,4,2)
FROM PSCONDUCTORESVIAJE PSV
JOIN PSASIGNACIONVIAJE PSA ON(PSA.NCLAVEEMPRESA = PSV.NCLAVEEMPRESA AND PSA.NCLAVEASIGNACIONVIAJE = PSV.NCLAVEASIGNACION AND PSV.NCLAVEAUTOBUS = PSA.NCLAVEAUTOBUS)
JOIN PSCORRIDASVIAJE PCV ON(PCV.NCLAVEENPRESA = PSA.NCLAVEEMPRESA AND PCV.NCLAVEASIGNACION = PSA.NCLAVEASIGNACIONVIAJE)
JOIN PSCORRIDASACTIVAS PCA ON(PCA.NCLAVEEMPESA = PCV.NCLAVEENPRESA AND PCA.NCLAVECORRIDA = PCV.NCLAVECORRIDA AND PCA.FFECHASALIDAINICIO = PCV.FFECHASALIDAINICIO AND PCA.NVERSION = PCV.NVERSION)
WHERE PSV.NCLAVEEMPRESA =:1 AND PSV.NCLAVEPERSONA =:2 AND PSA.AESTADOASIGNACION != 'C'
ORDER BY PSA.NCLAVEASIGNACIONVIAJE DESC,PSA.FCRFECHA DESC
LIMIT 1;

SELECT aut.NNUMEROECONOMICO 
from ETTRIPULACION trip
join GCAUTOBUSES aut on (aut.NCLAVEEMPRESA = trip.NCLAVEEMPRESA and aut.NCLAVEAUTOBUS = trip.NCLAVEAUTOBUS)
where trip.NCLAVEEMPRESA =:1 and trip.NCLAVEPERSONAASIGANDA =:2;

SELECT FECHA_LLEGADA
FROM LLEGADA_PLAN_RAC
WHERE NCLAVEEMPESA =:1
AND NCLAVEPERSONA =:2
ORDER BY FFECHASALIDAINICIO DESC LIMIT 1;

SELECT FECHA_RAC
FROM LLEGADA_PLAN_RAC
WHERE NCLAVEEMPESA =:1
AND NCLAVEPERSONA =:2
ORDER BY FFECHASALIDAINICIO DESC LIMIT 1;

SELECT TRIM(PER.ANOMBRES) || ' ' || TRIM(PER.AAPELLIDOS)
FROM GCPERSONAS PER
WHERE PER.NCLAVEEMPRESA =:1 AND PER.NCLAVEPERSONA =:2;

SELECT per.ACLAVEEMPLEADO
from GCPERSONAS per
where per.NCLAVEEMPRESA =:1 and per.NCLAVEPERSONA =:2;

SELECT trim(bas.ANOMBREBASE)
from GCPERSONAS per
JOIN GCOFICINAS OFI ON (OFI.ACLAVEOFICINA = PER.ACLAVEOFICINA and ofi.NCLAVEEMPRESA = per.NCLAVEEMPRESA)
join GCBASES bas on (bas.NCLAVEBASE = OFI.NCLAVEBASE and bas.NCLAVEEMPRESA = per.NCLAVEEMPRESA)
where per.NCLAVEEMPRESA =:1 and per.NCLAVEPERSONA =:2;

SELECT GCE.NOMBRE FROM GCPERSONAS GCP INNER JOIN GCEMPRESAS GCE ON (GCE.CLAVEEMPRESA = GCP.NEMPRESAALTERNA) WHERE GCP.NCLAVEEMPRESA =:1 AND GCP.NCLAVEPERSONA =:2;

SELECT trim(est.ADESCRIPCION)
from ETESTADOACTUALCOND ult
join ETESTADOSCONDUCTOR est on (est.NCLAVEEMPRESA = ult.NCLAVEEMPRESA and est.ACLAVEESTADOCONDUCTOR = ult.ACLAVEESTADOCONDUCTOR)
where ult.HFECHASERVIDOR <= CURRENT_DATE and  ult.NCLAVEEMPRESA =:1 and ult.NCLAVEPERSONA =:2 
order by ult.NCONSECUTIVO desc LIMIT 1;

SELECT PST.ATIPO 
FROM GCPERSONAS  GCP 
INNER JOIN PSTIPOSOPERADOR PST ON (PST.NCLAVEEMPRESA = GCP.NCLAVEEMPRESA AND PST.NCLAVETIPO = GCP.TIPOOPERADOR) 
WHERE GCP.NCLAVEEMPRESA =:1 
AND GCP.NCLAVEPERSONA =:2;

SELECT PER.NIMSS
from GCPERSONAS per
where per.NCLAVEEMPRESA =:1 and per.NCLAVEPERSONA =:2;

SELECT trim(PER.ATELEFONO1)
from GCPERSONAS per
where per.NCLAVEEMPRESA =:1 and per.NCLAVEPERSONA =:2;

SELECT TRIM(trim(ofi.ACLAVEOFICINA) || '; ' || trim(ofi.ANOMBREOFICINA) || '; ' || trim(ofi.ACALLE) || '; ' || trim(ofi.ANUMERO) || '; ' || trim(ofi.ACOLONIA) || '; ' || trim(ofi.AMUNICIPIODELEG) || '; ' || trim(est.ADESCRIPCIONESTADO) || '; ' || ofi.NCODIGOPOSTAL)
from GCPERSONAS as per
join GCOFICINAS as ofi
on (per.NCLAVEEMPRESA = ofi.NCLAVEEMPRESA and per.ACLAVEOFICINA = ofi.ACLAVEOFICINA)
join GCESTADOS as est on (ofi.NCLAVEEMPRESA = est.NCLAVEEMPRESA and ofi.ACLAVEESTADO = est.ACLAVEESTADO)
where per.NCLAVEEMPRESA =:1 and per.NCLAVEPERSONA =:2;

SELECT FECHA_LLEGADA
FROM LLEGADA_PLAN_RAC
WHERE NCLAVEEMPESA =:1
AND NCLAVEPERSONA =:2
ORDER BY FFECHASALIDAINICIO DESC LIMIT 1;

SELECT FECHA_RAC
FROM LLEGADA_PLAN_RAC
WHERE NCLAVEEMPESA =:1
AND NCLAVEPERSONA =:2
ORDER BY FFECHASALIDAINICIO DESC LIMIT 1;

SELECT FECHA_RAC
FROM LLEGADA_PLAN_RAC
WHERE NCLAVEEMPESA =:1
AND NNUMEROECONOMICO =:2
ORDER BY FFECHASALIDAINICIO DESC LIMIT 1;

SELECT TRIM(PER.ANOMBRES) || ' ' || TRIM(PER.AAPELLIDOS)
FROM GCPERSONAS PER
WHERE PER.NCLAVEEMPRESA =:1 AND PER.NCLAVEPERSONA =:2;

SELECT TRIM(EST.ADESCRIPCION)
FROM ETESTADOACTUALCOND ULT
JOIN ETESTADOSCONDUCTOR EST ON (EST.NCLAVEEMPRESA = ULT.NCLAVEEMPRESA AND EST.ACLAVEESTADOCONDUCTOR = ULT.ACLAVEESTADOCONDUCTOR)
WHERE ULT.HFECHASERVIDOR <= CURRENT_DATE AND  ULT.NCLAVEEMPRESA =:1 AND ULT.NCLAVEPERSONA =:2 
ORDER BY ULT.NCONSECUTIVO DESC LIMIT 1;

SELECT PST.ATIPO 
FROM GCPERSONAS  GCP 
INNER JOIN PSTIPOSOPERADOR PST ON (PST.NCLAVEEMPRESA = GCP.NCLAVEEMPRESA AND PST.NCLAVETIPO = GCP.TIPOOPERADOR) 
WHERE GCP.NCLAVEEMPRESA =:1 
AND GCP.NCLAVEPERSONA =:2;

SELECT TRIM(BAS.ANOMBREBASE)
FROM GCPERSONAS PER
JOIN GCOFICINAS OFI ON (OFI.ACLAVEOFICINA = PER.ACLAVEOFICINA AND OFI.NCLAVEEMPRESA = PER.NCLAVEEMPRESA)
JOIN GCBASES BAS ON (BAS.NCLAVEBASE = OFI.NCLAVEBASE AND BAS.NCLAVEEMPRESA = PER.NCLAVEEMPRESA)
WHERE PER.NCLAVEEMPRESA =:1 AND PER.NCLAVEPERSONA =:2;

SELECT GCE.NOMBRE FROM GCPERSONAS GCP INNER JOIN GCEMPRESAS GCE ON (GCE.CLAVEEMPRESA = GCP.NEMPRESAALTERNA) WHERE GCP.NCLAVEEMPRESA =:1 AND GCP.NCLAVEPERSONA =:2;

SELECT AUT.NNUMEROECONOMICO 
FROM ETTRIPULACION TRIP
JOIN GCAUTOBUSES AUT ON (AUT.NCLAVEEMPRESA = TRIP.NCLAVEEMPRESA AND AUT.NCLAVEAUTOBUS = TRIP.NCLAVEAUTOBUS)
WHERE TRIP.NCLAVEEMPRESA =:1 AND TRIP.NCLAVEPERSONAASIGANDA =:2;

SELECT SUBSTR(TO_CHAR(CURRENT_DATE,'YYYY-MM-DD'),9,2) || '/' || SUBSTR(TO_CHAR(CURRENT_DATE,'YYYY-MM-DD'),6,2) || '/' || SUBSTR(TO_CHAR(CURRENT_DATE,'YYYY-MM-DD'),1,4);

SELECT 
CASE PER.NEMPRESAALTERNA
WHEN '2' THEN 'ETN'
WHEN '16' THEN 'TURISTAR'
WHEN '0' THEN 'NO_ESPECIFICADO'
END
FROM GCPERSONAS PER WHERE PER.NCLAVEEMPRESA =:1 AND PER.NCLAVEPERSONA =:2;

SELECT TRIM(PER.ANOMBRES) || ' ' || TRIM(PER.AAPELLIDOS)
FROM GCPERSONAS PER
WHERE PER.NCLAVEEMPRESA =:1 AND PER.NCLAVEPERSONA =:2;

SELECT PER.ACLAVEEMPLEADO
FROM GCPERSONAS PER
WHERE PER.NCLAVEEMPRESA =:1 AND PER.NCLAVEPERSONA =:2;

SELECT trim(bas.ANOMBREBASE)
from GCPERSONAS per
JOIN GCOFICINAS OFI ON (OFI.ACLAVEOFICINA = PER.ACLAVEOFICINA and ofi.NCLAVEEMPRESA = per.NCLAVEEMPRESA)
join GCBASES bas on (bas.NCLAVEBASE = OFI.NCLAVEBASE and bas.NCLAVEEMPRESA = per.NCLAVEEMPRESA)
where per.NCLAVEEMPRESA =:1 and per.NCLAVEPERSONA =:2;

SELECT CASE WHEN GCP.LCONDUCTOR = x'01' THEN 'Conductor' ELSE 'Personal de tierra' END AS TIPOPERSONA
FROM GCPERSONAS GCP WHERE GCP.NCLAVEEMPRESA =:1
AND GCP.NCLAVEPERSONA =:2;

SELECT SUBSTR(TO_CHAR(CURRENT_DATE,'YYYY-MM-DD'),9,2) || '/' || SUBSTR(TO_CHAR(CURRENT_DATE,'YYYY-MM-DD'),6,2) || '/' || SUBSTR(TO_CHAR(CURRENT_DATE,'YYYY-MM-DD'),1,4);

SELECT 
CASE PER.NEMPRESAALTERNA
WHEN '2' THEN 'ETN'
WHEN '16' THEN 'TURISTAR'
WHEN '0' THEN 'NO_ESPECIFICADO'
END
FROM GCPERSONAS PER WHERE PER.NCLAVEEMPRESA =:1 AND PER.NCLAVEPERSONA =:2;

SELECT TRIM(PER.ANOMBRES) || ' ' || TRIM(PER.AAPELLIDOS)
FROM GCPERSONAS PER
WHERE PER.NCLAVEEMPRESA =:1 AND PER.NCLAVEPERSONA =:2;

SELECT PER.ACLAVEEMPLEADO
FROM GCPERSONAS PER
WHERE PER.NCLAVEEMPRESA =:1 AND PER.NCLAVEPERSONA =:2;

SELECT PER.ACLAVEOFICINA
FROM GCPERSONAS PER
WHERE PER.NCLAVEEMPRESA =:1 AND PER.NCLAVEPERSONA =:2;